name: Run Every 5 Minutes

on:
  schedule:
    - cron: '*/5 * * * *'   # Runs every 5 minutes
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Example step
        run: echo "This workflow runs every 5 minutes!"
